name = "cumulus"

compatibility_date = "2024-04-26"
pages_build_output_dir = ".svelte-kit/cloudflare"

[[d1_databases]]
binding = "auth"
database_name = "auth"
database_id = "b612af83-cbb1-45fd-8558-c681cd1dab2c"

[vars]
AUTH_GOOGLE_ID = "426398616997-9p4i9av1788r79t525f7aocokm7p10qf.apps.googleusercontent.com"
